### ISSUE TITLE
post_charge() accepts Net::Stripe::Customer but Net::Stripe::Charge doesn't.

### ISSUE THREAD

**Issue by ghost** [lukec/stripe-perl#94]
Net::Stripe::post_charge() accepts a Net::Stripe::Customer|HashRef|Str for $customer, but passes it directly to the Net::Stripe::Charge constructor, where customer isa 'Maybe[Str]'.

**Comment by sherrardb** [comment]
even after adding `Net::Stripe::Customer` to the TypeConstraint for `Net::Stripe::Charge`, the post fails because the customer object is not serialized properly. 

```
~$ perl -Mstrict -Mwarnings -mNet::Stripe -e 'my $stripe = Net::Stripe->new(api_key => $ENV{STRIPE_API_KEY});
my $fake_card = {
  number=> "4242-4242-4242-4242",
  exp_month=> 12,
  exp_year=> 2030,
  cvc=> 123
};
my $token = $stripe->post_token(card => $fake_card);
my $customer = $stripe->post_customer(card => $token->id);
$stripe->post_charge(amount=> 250, currency=> "usd", customer=> $customer);'
Error: invalid_request_error - No such customer: Net::Stripe::Customer=HASH(0x408e728) On parameter: customer
Card error: resource_missing
```
similar applies for passing a customer hashref as well as card objects and hashrefs, 

my initial inclination, per #134, was to update the `post_charge()` to handle these properly. but my current thinking is that since this calling form is broken, we can guarantee that nobody is currently using it, and therefore it is better to remove those TypeConstraints from the Kavorka signature rather than complicating the code and creating future maintenance issues.
